export const DATA = [
  {
    title: "Main dishes",
    data: [
      "Pizza",
      "Burger",
      "Risotto",
      "Pizza",
      "Burger",
      "Risotto",
      "Pizza",
      "Burger",
      "Risotto",
      "Pizza",
      "Burger",
      "Risotto",
      "Pizza",
      "Burger",
      "Risotto",
      "Pizza",
      "Burger",
      "Risotto",
      "Pizza",
      "Burger",
      "Risotto",
      "Pizza",
      "Burger",
      "Risotto",
      "Pizza",
      "Burger",
      "Risotto",
    ],
  },
  {
    title: "Sides",
    data: [
      "French Fries",
      "Onion Rings",
      "Fried Shrimps",
      "French Fries",
      "Onion Rings",
      "Fried Shrimps",
      "French Fries",
      "Onion Rings",
      "Fried Shrimps",
      "French Fries",
      "Onion Rings",
      "Fried Shrimps",
      "French Fries",
      "Onion Rings",
      "Fried Shrimps",
      "French Fries",
      "Onion Rings",
      "Fried Shrimps",
      "French Fries",
      "Onion Rings",
      "Fried Shrimps",
      "French Fries",
      "Onion Rings",
      "Fried Shrimps",
      "French Fries",
      "Onion Rings",
      "Fried Shrimps",
    ],
  },
  {
    title: "Drinks",
    data: [
      "Water",
      "Coke",
      "Beer",
      "Water",
      "Coke",
      "Beer",
      "Water",
      "Coke",
      "Beer",
      "Water",
      "Coke",
      "Beer",
      "Water",
      "Coke",
      "Beer",
      "Water",
      "Coke",
      "Beer",
      "Water",
      "Coke",
      "Beer",
      "Water",
      "Coke",
      "Beer",
      "Water",
      "Coke",
      "Beer",
    ],
  },
  {
    title: "Desserts",
    data: [
      "Cheese Cake",
      "Ice Cream",
      "Cheese Cake",
      "Ice Cream",
      "Cheese Cake",
      "Ice Cream",
      "Cheese Cake",
      "Ice Cream",
      "Cheese Cake",
      "Ice Cream",
      "Cheese Cake",
      "Ice Cream",
      "Cheese Cake",
      "Ice Cream",
      "Cheese Cake",
      "Ice Cream",
      "Cheese Cake",
      "Ice Cream",
    ],
  },
];
